### ISSUE TITLE
problem with the display of the gender of the word

### ISSUE THREAD

**Issue by TheTakylo** [Songkeys/Translateer#11]
Translating from EN to IT "New" gives me Nuova(feminine)

I have the impression that it takes into account what google displays to describe the word but it should not because its not part of the translation

**Comment by songkeys** [comment]
Hi. Thank you for the report. I just fixed this in this commit:

https://github.com/Songkeys/Translateer/commit/a092da1a1ec110d00061f38b6f11d973ea2a5236#diff-148bacb6839f9d7e10901515876440d2e966036b4b9ff4ef8562349353df35d1L128

Could you try again to see if it's working now?

**Comment by TheTakylo** [comment]
it work perfect
