### ISSUE TITLE
Hebrew fails with error 500

### ISSUE THREAD

**Issue by Nuklon** [Songkeys/Translateer#12]
It doesn't matter which text you enter, they all fail, for example:
http://localhost:8999/api?text=hello&from=en&to=he

```json
{"statusCode":500,"error":"Internal Server Error","message":"Evaluation failed: TypeError: Cannot read properties of undefined (reading 'parentElement')\n    at isInRecentScope (pptr://__puppeteer_evaluation_script__:6:36)\n    at pptr://__puppeteer_evaluation_script__:22:13"}
```

All other languages seem to be working OK. It might be because Hebrew is RTL?

**Comment by Nuklon** [comment]
Nevermind, seems Google is now using iw code on site for hebrew. Website also maps he correctly.

**Comment by songkeys** [comment]
> It might be because Hebrew is RTL?

I'm not sure. I haven't considered RTL problem but it's fine with arabic language IIRC.

> seems Google is now using iw code on site for hebrew

What is iw code? Could you give me some clues so I can fix this?

**Comment by Nuklon** [comment]
The language code for Hebrew is now "iw" on Google Translate, it used to be "he". If you pass in "iw" to Translateer it's working correctly.

**Comment by songkeys** [comment]
Ah, I see. Thanks for the helpful information for anyone else who may come across this issue.
