### ISSUE TITLE
The translated results are not the same as the web version

### ISSUE THREAD

**Issue by nanoia** [Songkeys/Translateer#2]
It looks like the problem mentioned in that [issue](https://github.com/vitalets/google-translate-api/issues/70) still exists。

My request url is as follows:
`/api?text=別れてしまうから燃え上がる。結婚する逢花。彼女の結婚式に出席するため、帰省してきた幼馴染の男。2人は幼稚園から●校までずっと一緒だった。大人になってもずっとそばにいる、なんとなくそう思っていた。けれど、気づけば別々の道を歩んでいた2人。再会した男女は、今までの思い出とこれからの未来に想いをふける。「ずっと、好きだった…」「遅いよ、バカ…」結婚式直前の三日間。人生はやり直せない。幼馴染の男女は、残りの時間を使い果たした…。&from=auto&to=zh-CN` 
The response:
```
{
    "result": "它烧坏了，因为它破坏了。",
    "pronunciation": "Tā shāo huàile, yīnwèi tā pòhuàile. Xiǎngshòu hūnyīn. Yīgèrén huí jiā cānjiā tā de hūnlǐ. Liǎng gèrén cóng yòu'éryuán dào xuéxiào. Jíshǐ wǒ chéngle yīgè chéngnián rén, wǒ yěshì qiáomài miàn, wǒ zhème rènwéi. Dàn rúguǒ nǐ zhùyì dào, liǎng gè rén zǒule yīgè dúlì de dàolù. Tuánjù de nánnǚ shì dào mùqián wéizhǐ de huíyì hé wèilái wèilái de wèilái. “Wǒ hěn xǐhuān tā hěn zhǎng yīduàn shíjiān......” Màn man, yúchǔn......“Zài hūnlǐ qián sān tiān. Shēnghuó bìng méiyǒu chángshì zuò. Yīgè tóngnián de péngyǒu nánxìng hé nǚxìng shíxiànle shèng xià de shíjiān......",
    "from": {
        "iso": "ja",
        "pronunciation": "Wakarete shimaukara moeagaru. Kekkon suru hōka. Kanojo no kekkonshiki ni shusseki suru tame, kisei shite kita osananajimi no otoko. 2-Ri wa yōchien kara ● kō made zutto isshodatta. Otona ni natte mo zutto soba ni iru, nantonaku sō omotte ita. Keredo, kidzukeba betsubetsu no michi o ayunde ita 2-ri. Saikai shita danjo wa, ima made no omoide to korekara no mirai ni omoi o fukeru. `Zutto, sukidatta…'`osoi yo, baka…' kekkonshiki chokuzen no mikkakan. Jinsei wa yarinaosenai. Osananajimi no danjo wa, nokori no jikan o tsukaihatashita…."
    }
}
```
The result from translate.google.com:
`它会燃烧，因为它会分解。 艾卡要结婚了。 回到家乡参加婚礼的儿时玩伴。 从幼儿园到学校，两人一直在一起。 即使长大成人，我也一直在身边，不知怎的，我也是这么想的。 然而，当我注意到时，他们走上了不同的道路。 重逢的男女，沉醉在回忆和未来中。 “我一直很喜欢……” “迟到了，笨蛋……” 婚礼前三天。 人生无法重来。 青梅竹马的少男少女们，时间已经不多了……`

**Comment by songkeys** [comment]
Thank you for this report.

It seems that google translate has a detection for puppeteer. I just fixed this with [stealth](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) in <https://github.com/Songkeys/Translateer/commit/7a323c8d6d2111c6e5cc821e7605c2cf003c34af>. Also with a fix when there is multiple sentences.

The translations should be accurate now.

Try this:

<https://t.song.work/api?text=別れてしまうから燃え上がる。結婚する逢花。彼女の結婚式に出席するため、帰省してきた幼馴染の男。2人は幼稚園から●校までずっと一緒だった。大人になってもずっとそばにいる、なんとなくそう思っていた。けれど、気づけば別々の道を歩んでいた2人。再会した男女は、今までの思い出とこれからの未来に想いをふける。「ずっと、好きだった…」「遅いよ、バカ…」結婚式直前の三日間。人生はやり直せない。幼馴染の男女は、残りの時間を使い果たした…。&from=auto&to=zh-CN>
