### ISSUE TITLE
Error translating to English

### ISSUE THREAD

**Issue by dorawei** [Songkeys/Translateer#3]
`https://t.song.work/api?text=%E4%BD%A0%E5%A5%BD&from=auto&to=en` 
would cause timeout error:
`{"statusCode":500,"error":"Internal Server Error","message":"waiting for selector `span[data-language-for-alternatives=en]` failed: timeout 30000ms exceeded"}`

However with en-US it also didn't work
`https://t.song.work/api?text=%E4%BD%A0%E5%A5%BD&from=auto&to=en-US`
`{"statusCode":500,"error":"Internal Server Error","message":"Evaluation failed: TypeError: Cannot read properties of undefined (reading 'click')\n    at <anonymous>:3:32"}`

**Comment by songkeys** [comment]
Hi. Thank you for reporting.

> <https://t.song.work/api?text=%E4%BD%A0%E5%A5%BD&from=auto&to=en> would cause timeout error

I can't reproduce this issue on my local machine but it did appear on the production env. I just tried a fix. Could you try again? It seems working for me now.

> However with en-US it also didn't work

There is no `en-US` language code. Only `en` should work (now).

**Comment by dorawei** [comment]
It works now with the updated selector, thanks so much for fixing this!
