### ISSUE TITLE
Set proxy

### ISSUE THREAD

**Issue by therealsamsquanch** [Songkeys/Translateer#4]
I want to balance the number of requests made by each IP, setting a different proxy on each API call. Is it possible?

**Comment by songkeys** [comment]
I haven't tried that. But I think it's possible. We can use https://github.com/gajus/puppeteer-proxy or https://github.com/Cuadrix/puppeteer-page-proxy on page basis or request basis.

Have you got rate limited so far?

**Comment by therealsamsquanch** [comment]
Puppeteer-page-proxy's community appears to be more involved and trying to solve issues by themselves.

I haven't started using it yet. Launched on docker, and it appears to be working, but I have very large articles that I would like to translate. The character limit is 5000, and I'm assuming 1 request per second, it could take over a month to finish. Since I already have a few proxies available, maybe I could speed things up.

**Comment by songkeys** [comment]
> Puppeteer-page-proxy's community appears to be more involved and trying to solve issues by themselves.

However, considering this project is only for educational purposes (for some reason), I would not take time to implement proxy as a bypass for overloaded requests (I'm not sure how frequent it would be to trigger rate limitation to require a proxy). But a PR of an opt-in feature is welcome anyway!

> I have very large articles that I would like to translate

I don't think what you need is proxy but "paralleled requests". See below.

>  The character limit is 5000

Yes. This project hasn't supported articles longer than 5000 chars yet. I think it's doable though but takes time. So far, you have to split your articles manually before requesting.

>  I'm assuming 1 request per second

You can send paralleled requests. The default maximum concurrent request limit, as said in the readme, is `5`, which can be increased by setting env `PAGE_COUNT` to another bigger number. But also note that each page would take up some memory as it is a chromium tab internally. I haven't tried and calculated the accurate memory impact of each page. You have to test it yourself and set an appropriate value for your large requests.

**Comment by therealsamsquanch** [comment]
Got it. Thanks!

**Comment by ringge** [comment]
Referencing this article https://pixeljets.com/blog/how-to-set-proxy-in-puppeteer/
So it'd be much simpler to set proxy by adding this args, I've tested and it worked perfectly
const browser = await puppeteer.launch({
    headless: false,
    args: [ '--proxy-server=http://your-proxy-host:3128' ]
  });

**Comment by songkeys** [comment]
@ringge 

Yes, that is indeed the correct method for setting a proxy in Puppeteer. Could you please let me know what issue you are facing that necessitates the use of a proxy?

**Comment by ringge** [comment]
> @ringge
> 
> Yes, that is indeed the correct method for setting a proxy in Puppeteer. Could you please let me know what issue you are facing that necessitates the use of a proxy?

Oh I'm not facing any issues with translateer, just kind of looking into proxy to use Puppeteer for other projects

**Comment by therealsamsquanch** [comment]
> @ringge
> 
> Yes, that is indeed the correct method for setting a proxy in Puppeteer. Could you please let me know what issue you are facing that necessitates the use of a proxy?

Just to add context, due to CGNAT, some residential IP range are flagged as bot/risky on Google. So, to make a simple search on Google, if I'm not logged into my account, it asks to first solve a captcha. While there's no captcha when using Translate, it appears that the responses are throttled. So I've been using a proxy to reduce such problems.

Also, I believe that they stop responding on Translate if you always send larger texts. If I send one to three short sentences per query, it works fine. If I keep sending around 1000+ characters, it stops responding after maybe 50 queries, even if there's a 2-second delay between the requests. Doesn't matter if I restart the container, it still won't answer. It does if I change the proxy IP. This has been so limiting that I'm looking into LLMs to keep translating. Llama 2 is cheap and does a decent job depending on the language, but I haven't found an uncensored version hosted. If it's not uncensored, it will refuse to translate texts that contain violence or that it finds even mildly aggressive.

**Comment by ringge** [comment]
> > @ringge
> > Yes, that is indeed the correct method for setting a proxy in Puppeteer. Could you please let me know what issue you are facing that necessitates the use of a proxy?
> 
> Just to add context, due to CGNAT, some residential IP range are flagged as bot/risky on Google. So, to make a simple search on Google, if I'm not logged into my account, it asks to first solve a captcha. While there's no captcha when using Translate, it appears that the responses are throttled. So I've been using a proxy to reduce such problems.
> 
> Also, I believe that they stop responding on Translate if you always send larger texts. If I send one to three short sentences per query, it works fine. If I keep sending around 1000+ characters, it stops responding after maybe 50 queries, even if there's a 2-second delay between the requests. Doesn't matter if I restart the container, it still won't answer. It does if I change the proxy IP. This has been so limiting that I'm looking into LLMs to keep translating. Llama 2 is cheap and does a decent job depending on the language, but I haven't found an uncensored version hosted. If it's not uncensored, it will refuse to translate texts that contain violence or that it finds even mildly aggressive.

Oh that's right, I tried to increase amount of requests and it seems the result is similar to what you described, maybe it got rate limited
