### ISSUE TITLE
Translating to en doesn't work

### ISSUE THREAD

**Issue by therealsamsquanch** [Songkeys/Translateer#5]
Tested with an Italian sentence: _"Non parteciperò più ai tornei dello slam o dell'Atp'. In carrier ha vinto venti titoli del grande slam e in tutto 103 tornei da professionista"_.

https://t.song.work/api?text=Non%20parteciper%C3%B2%20pi%C3%B9%20ai%20tornei%20dello%20slam%20o%20dell%27Atp%27.%20In%20carriera%20ha%20vinto%20venti%20titoli%20del%20grande%20slam%20e%20in%20tutto%20103%20tornei%20da%20professionista&from=auto&to=en

Result from `auto` to `en`, and  `it` to `en`:

```
result: "Non parteciperò più ai tornei dello slam o dell'Atp'. In carrier ha vinto venti titoli del grande slam e in tutto 103 tornei da professionista"
from :  
   iso: "en"
```

https://t.song.work/api?text=Non%20parteciper%C3%B2%20pi%C3%B9%20ai%20tornei%20dello%20slam%20o%20dell%27Atp%27.%20In%20carriera%20ha%20vinto%20venti%20titoli%20del%20grande%20slam%20e%20in%20tutto%20103%20tornei%20da%20professionista&from=auto&to=es

Result from `auto` to `es`:

```
result: "Ya no participaré en torneos de slam o ATP'. En su carrera ha ganado veinte títulos de Grand Slam y un total de 103 torneos profesionales"
from :  
   iso: "it"
```

**Comment by songkeys** [comment]
Thanks for reporting. I'll take a look during the weekend.

**Comment by songkeys** [comment]
Could you please try again?

This should be fixed in https://github.com/Songkeys/Translateer/commit/38a7ce37c75f752ef3a727cf3da3d7f741fdb7f4

**Comment by songkeys** [comment]
There is still an error case 🤔 let me reopen this

**Comment by songkeys** [comment]
should be fixed in cb0b15163d3d68662838242988496e4161e0c5cf

you may try again

**Comment by therealsamsquanch** [comment]
Sorry for the late reply. Made about 5 calls. Worked fine 3 times, the other two I got this:

```
'statusCode' => 500,
'error' => 'Internal Server Error',
'message' => 'waiting for selector `div[aria-live=polite] span` failed: timeout 30000ms exceeded'
```

**Comment by songkeys** [comment]
Did you make the same call (https://t.song.work/api?text=Non%20parteciper%C3%B2%20pi%C3%B9%20ai%20tornei%20dello%20slam%20o%20dell%27Atp%27.%20In%20carriera%20ha%20vinto%20venti%20titoli%20del%20grande%20slam%20e%20in%20tutto%20103%20tornei%20da%20professionista&from=auto&to=en ) 5 times? I made 30+ times and can't reproduce it. 🤔

**Comment by therealsamsquanch** [comment]
I've found the problem. I was using PHP's rtrim() and it was silently failing, returning an empty string. If the parameter `text` receives an empty string, you get the same error I had: https://t.song.work/api?text=&to=en

I'll close the issue, as it's now fixed. Thank you! :)
