### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by therealsamsquanch** [Songkeys/Translateer#7]
Every request adds a bit more to the memory. Feeding larger sets of text, around 4000 characters, makes it more evident.

I was wondering if it could be some problem with Docker, so I've also tried running it on Ubuntu 20 VM, with 10GB RAM. The problem persists. It starts at 2.2GB RAM usage and consumption grows until there's no memory left.

To avoid crashing the VM, I'm closing all tabs and reopening on regular intervals. I've found that it's not necessary to close the browser itself to free the memory, just the tabs.

Is anyone else seeing this problem?

**Comment by songkeys** [comment]
I'm not sure where the memory leak comes from.

Question:

1. How many memory grows after each request? I assume every query on the page will leave a history? But if the memory grows a lot it might not be the case.

2. Does the memory keep growing even after 1 hour? Because here I refresh pages every 1 hour. I think they should have the same effect as the reopening?

https://github.com/Songkeys/Translateer/blob/5b4ec8bdaf0bd6ce7ca87e94c36d398381fad33f/src/browser/pagepool.ts#L48-L59

**Comment by therealsamsquanch** [comment]
**How many memory grows after each request? I assume every query on the page will leave a history? But if the memory grows a lot it might not be the case.**
Around 10MB every few seconds. I'm running two instances, 6 tabs each

**Does the memory keep growing even after 1 hour? Because here I refresh pages every 1 hour. I think they should have the same effect as the reopening?**
Closing the tabs is probably unnecessary, but I decided to go the extra length to avoid more problems. I have to close and reopen tabs every 20 minutes, as this is enough time to raise RAM consumption by 5GB.

**Comment by songkeys** [comment]
Thank you for your report. I'll take a look during this weekend!

**Comment by songkeys** [comment]
This looks like an issue with puppeter itself https://github.com/puppeteer/puppeteer/issues/5893

The current solution is to close the browser and restart it. I made this change in commit https://github.com/Songkeys/Translateer/commit/91b3d229ae85d4e95482677c009f50bd6f09e533. Let me know if this solves for you.

**Comment by therealsamsquanch** [comment]
Memory leak persists, but hopefully closing the browser every N minutes will help other people with this issue. Thanks!
