### ISSUE TITLE
ARM64 docker-compose

### ISSUE THREAD

**Issue by GeekWorkCode** [Songkeys/Translateer#9]
npm ERR! code 1
npm ERR! path /usr/app/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  sudo apt install chromium
npm ERR! 
npm ERR! 
npm ERR!  sudo apt install chromium-browser
npm ERR! 
npm ERR! ERROR: Failed to set up Chromium r1095492! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error
npm ERR!     at handleArm64 (/usr/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:137:11)
npm ERR!     at BrowserFetcher.download (/usr/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:284:13)
npm ERR!     at async downloadBrowser (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:61:5)

browserless/chrome works properly. However, node failed to start

**Comment by songkeys** [comment]
Hi. May I know if you resolved this issue?

**Comment by GeekWorkCode** [comment]
> 
I found an available node Dockefile.
1、Build node locally yourself
2、Replace the node name in docker-compose.yml
`FROM node:16-bullseye-slim

ENV DEBIAN_FRONTEND noninteractive

# for arm64 support we need to install chromium provided by debian
# npm ERR! The chromium binary is not available for arm64.
# https://github.com/puppeteer/puppeteer/issues/7740

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN apt-get update && \
    apt-get install -y wget gnupg && \
    apt-get install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
        libgtk2.0-0 libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1 libasound2 && \
    apt-get install -y chromium && \
    apt-get clean

# Just for development - not required in any way
#RUN apt-get install -y vim bash

WORKDIR /src
COPY ./src /src

# Should be better move this into a package.json?
#RUN npm i puppeteer express body-parser temp
#RUN npm install

CMD ["node", "webservices.js"]`

**Comment by GeekWorkCode** [comment]
FROM node:16-bullseye-slim

ENV DEBIAN_FRONTEND noninteractive

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN apt-get update && \
    apt-get install -y wget gnupg && \
    apt-get install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
        libgtk2.0-0 libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1 libasound2 && \
    apt-get install -y chromium && \
    apt-get clean

WORKDIR /src
COPY ./src /src

CMD ["node", "webservices.js"]
